### PR TITLE
make it possible to specify multiple syslog endpoints

### PR DESCRIPTION
**Pull request by Bonko**

### CODE REVIEW

**Comment by Bonko** [comment]
PTAL @Jimdo/werkzeugschmiede

**Comment by Luzifer** [comment]
This will not work because you do have one channel in which you put items. Additional you have two routines reading from that channel. So every routine will get a subset of all messages.

**Comment by Bonko** [comment]
current status:
```
Apr 20 13:00:11 ip- dockerlogstream[8629]: fatal error: concurrent map read and map write 
Apr 20 13:00:11 ip- dockerlogstream[8629]: goroutine 18 [running]:
Apr 20 13:00:11 ip- dockerlogstream[8629]: runtime.throw(0x8cb3ee, 0x21)
Apr 20 13:00:11 ip- dockerlogstream[8629]:         /usr/lib/go/src/runtime/panic.go:596 +0x95 fp=0xc420229470 sp=0xc420229450
Apr 20 13:00:11 ip- dockerlogstream[8629]: runtime.mapaccess2_faststr(0x849c00, 0xc420152a50, 0xc42011061b, 0x7, 0x40e1cf, 0x8b86a0) 
Apr 20 13:00:11 ip- dockerlogstream[8629]:         /usr/lib/go/src/runtime/hashmap_fast.go:326 +0x50a fp=0xc4202294d0 sp=0xc420229470
Apr 20 13:00:11 ip- dockerlogstream[8629]: github.com/Jimdo/dockerlogstream/vendor/github.com/robertkrimen/otto.objectGetOwnProperty(0xc420059020, 0xc42011061b, 0x7, 0x8b86a0) 
Apr 20 13:00:11 ip- dockerlogstream[8629]:         /home/bonko/go/src/github.com/Jimdo/dockerlogstream/vendor/github.com/robertkrimen/otto/object_class.go:171 +0x6d fp=0xc420229520 sp=0xc4202294d0
```

**Comment by Bonko** [comment]
After we talked about this, it seems to be kind of ugly to implement, so we won't do it now

**Pull request closed without merging**
